### ISSUE TITLE
Documentation wrong..?

### ISSUE THREAD

**Issue by davidohlin** [datetime/weekday#1]
I was planning on using this but `weekday();` returns a number and not the day as a string, as it is stated in the documentation. 

I think it would be more reasonable to change the code to make it work as documented. Right now there's no way to get the current day represented as a string. What do you think?

Pretty new to Github and open source in general, but I'll happily make a PR to change it either way. What do you think?

**Comment by jonschlinkert** [comment]
welcome to the community! and you are correct! The `weekday();` example should be a string. 

I think we can just change [this code](https://github.com/datetime/weekday/blob/master/index.js#L16-L18) to:

``` js
  if (typeof num === 'undefined') {
    num = day;
  }
```

does that look ok to you?

A pr would be great. Don't worry too much about getting everything correct with the pr, I'd be happy to work through it with you. 

thanks!

**Comment by davidohlin** [comment]
Thank you!

Definitely! I'll try to not screw it up. 😉
